### ISSUE TITLE
sql注入漏洞的页面错误

### ISSUE THREAD

**Issue by cyber1c3** [tangxiaofeng7/SecExample#1]
完全按照 安装命令来，先clone 项目，然后起docker
没有修改任何东西，默认访问第一个sql的页面就出错了
![图片](https://user-images.githubusercontent.com/81949263/122917917-220e1900-d391-11eb-9f36-5a137ac31021.png)
  @@点击测试漏洞后就出现下面的报错
![图片](https://user-images.githubusercontent.com/81949263/122917746-ef642080-d390-11eb-88fe-bdfd7c7d109f.png)

>

**Comment by tangxiaofeng7** [comment]
应该是数据库服务出问题了，明天我看下。

**Comment by tangxiaofeng7** [comment]
已修复。应该是迭代的时候，数据库配置文件未修改为docker镜像的地址就进行了打包导致数据库连接失败。
